var NOME = " Roberto Junior";
var idade = 32;
var idade2 = 10;
var frase = "Japão é o melhor time do mundo";
//alert ("Bem vindo" + NOME + " idade " + idade);
//numero sem aspas é tratado como numero possibilitando soma, numero entra aspas é tratado como como string
//alert (idade + idade2)
//O comando replace troca palavras tanto no controle de log como na função alerta
//Comando toUpperCase torna tudo maiusculo
//Comando toLowerCase torna tudo minusculo
//as funções de calculo basico podem ser realizadas com as variaveis numéricas normalmente
console.log(NOME);
console.log(idade + idade2);
//console.log(frase.replace("Japão", "Brasil"));
//alerta (frase.replace("Japão", "Brasil"));
console.log(frase.toUpperCase())